import { WalletButton } from "@rainbow-me/rainbowkit";
import { useAccount, useDisconnect } from "wagmi";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { address, isConnected } = useAccount();
  const { disconnect } = useDisconnect();
  const router = useRouter();

  const handlerOne = async () => {
    console.log("Address before fetch:", address);

    try {
      const res = await fetch(`/api/login?address=${address}`, {
        method: "GET",
        headers: { "Content-Type": "application/json" },
      });

      if (!res.ok) {
        disconnect();
        throw new Error(`HTTP error! Status: ${res.status}`);
      } else {
        const userData = await res.json();
        router.push(`/${userData.user.role}`);
      }
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    if (isConnected) {
      handlerOne();
    }
  }, [isConnected]);

  const handler = (): void => {
    disconnect();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>fFyp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <WalletButton.Custom wallet="metamask">
          {({ ready, connect }) => {
            return (
              <button
                type="button"
                disabled={!ready}
                onClick={() => {
                  connect();
                }}
              >
                Metamask Login
              </button>
            );
          }}
        </WalletButton.Custom>

        {isConnected ? (
          <div>
            <p>{address}</p>
            <button onClick={handler}>Disconnect</button>
          </div>
        ) : (
          <div></div>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
